#!/bin/sh

echo "// Auto generated by build.sh" > version.h
echo "#ifndef VERSION" >> version.h
echo "#define VERSION \"$(cat ../version)\"" >> version.h
echo "#endif" >> version.h

arm-none-linux-gnueabi-gcc \
        -DDEBUG -O4 -Wall -lpthread \
        -I../externals/mongoose \
        -DMG_DISABLE_HTTP_DIGEST_AUTH \
        -DMG_DISABLE_MQTT \
        -DMG_DISABLE_MD5 \
        -DMG_DISABLE_JSON_RPC \
        -DMG_DISABLE_SOCKETPAIR \
        -o nx-remote-controller-daemon \
        api_server.c \
        command.c \
        input.c \
        lcd.c \
        led.c \
        liveview.c \
        main.c \
        ../externals/mongoose/mongoose.c \
        network.c \
        nx_model.c \
        osd.c \
        shutter.c \
        status.c \
        util.c \
    && cp -fv nx-remote-controller-daemon ../install/app/ \
    && cp -fv nx-remote-controller-daemon ../sd_install/remote/
