#!/bin/bash

# ========= force LCD on (crash on EVF) =========
st app disp lcd
sleep 1


INSTALL_PATH=/opt/storage/sdcard/app
TOOLS_PATH=$(mktemp -p /opt/usr -d tools.XXXXXX)
INSTALL_LOG=$TOOLS_PATH/install.log
YAD="chroot $TOOLS_PATH /usr/bin/yad"

tar -C $TOOLS_PATH -xvf $INSTALL_PATH/tools.tar
mkdir -pv $TOOLS_PATH/{dev,sbin,usr/sbin}
chown root:root $TOOLS_PATH/bin/busybox
chroot $TOOLS_PATH /bin/busybox --install -s
mknod $TOOLS_PATH/dev/null c 1 3

$INSTALL_PATH/install.sh &> $INSTALL_LOG
$YAD --text-info --filename=$INSTALL_LOG --tail

if [ -f /opt/storage/sdcard/nx-on-wake/on-wake ]; then
    rm -f /opt/storage/sdcard/nx-on-wake/on-wake
fi
rm -rf $TOOLS_PATH

sync;sync;sync;

/opt/usr/nx-on-wake/on-wake
